# Generated by Django 2.1.5 on 2019-12-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20191206_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
    ]
