# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-16 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60)),
                ('no_of_students', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.CharField(max_length=60)),
                
            ],
        ),
    ]
